trigger:
- main

pool:
  name: myAgentPool

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.10'
        addToPath: true

    - script: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
      displayName: 'Install dependencies'

    - script: |
        python -m unittest discover
      displayName: 'Run tests'

    - script: |
        zip -r $(Build.ArtifactStagingDirectory)/app.zip .
      displayName: 'Create ZIP package'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: $(Build.ArtifactStagingDirectory)
        ArtifactName: drop
        publishLocation: 'Container'

- stage: Deploy
  dependsOn: Build
  jobs:
  - job: DeployJob
    steps:
    - download: current
      artifact: drop

    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'ci-cd-connection'
        appName: 'ci-cd-udacity-shan'
        package: '$(Pipeline.Workspace)/drop/app.zip'
      displayName: 'Deploy to Azure WebApp'
