trigger:
- main

pool: 
  name: myAgentPool

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.8'
        addToPath: true

    - script: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
      displayName: 'Install dependencies'

    - script: |
        python -m unittest discover
      displayName: 'Run tests'

- stage: Deploy
  jobs:
  - job: DeployJob
    steps:
    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'ci-cd-connection'
        appName: 'ci-cd-udacity-shan'
        package: '$(System.DefaultWorkingDirectory)/**/*.zip'
      displayName: 'Deploy to Azure WebApp'
